### ISSUE TITLE
Allow to early return a task

### ISSUE THREAD

**Issue by Kjarrigan** [tonobo/task#6]
I want to do something like this:

```yaml
tasks:
  ci:
    cmds:
       - if [ -z "$CI" ]; then exit; end
       - task: cool.io # Do my custom stuff but only if CI-env is set
tasks:
  setups:
     - task: ci
     - ./install_deps.sh
```

So skip certain parts of a task if a condition is met. I could wrap it in a big if block like so:

```
- |
  if [ COND ]
  then
     # Do my custom stuff but only if CI-env is set
  end
```

but then I can't invoke subtasks and stuff.
