### ISSUE TITLE
Allow to pass arguments to a task

### ISSUE THREAD

**Issue by Kjarrigan** [tonobo/task#7]
Seems like this isn't supported at the moment but using environment variables feels not right for certain scenarios. What about addings something like `rake` does so

```bash
$ task api:request[/servers,-v]
```

```yaml
version: 2
tasks:
  desc: Fetch data from an API
  arguments:
     - PATH
     - ARG_WITH_DEFAULT: -s
  cmds:
     - curl {{.ARG_WITH_DEFAULT}} -H "Authorization: Bearer $TOKEN" https://example.com/v1{{.PATH}}
```

**Comment by Kjarrigan** [comment]
This is already possible as you can see here:
https://tonobo.github.io/task/#/usage?id=variables
```
task foo VAR1=2 "VAR2=Hello World"
```

For default values it is a bit more complicated.

```
expansions: 3

vars:
  DEFAULT_VAR1: 'Hello World'

tasks:
  dummy:
     cmds:
        - echo "{{if .VAR1}}{{.VAR1}}{{else}}{{.DEFAULT_VAR1}}{{end}}"
```
